apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec: #spec do deployment
  replicas: 1

  selector: # select utilizado para criar o service
    matchLabels:
      app: mysql-server
      tier: db

  template: #referente ao POD
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec:
      containers:
        - image: mysql:5.7
          name: mysql-server
          args: #ignorar lost+found para evitar error padrão
            - "--ignore-db-dir=lost+found"

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 23306

          volumeMounts: #monta o volume efetivamente
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql

      #definir volume
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim