apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app

spec:
  selector:
    matchLabels:
      app: app

  template:
    metadata:
      labels:
        app: app
    spec: 
      containers:
      - name: app
        #gcr.io/testes-desenvolvimento-260917/app-laravel@sha256:6c5ba12f881a2dd8397b6e96531c2286af20effbb84dae1d9ecddeed722cced5
        image: img-app-deployment
        command: ["/bin/sh", "-c", "ln -s /var/www /usr/share/nginx/html; /var/www/k8s/entrypoint.sh; php-fpm;"]
        ports:
        - containerPort: 9000

        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mysql-pass
              key: password

        # envFrom: 
        # - configMapRef:
        #     name: app-conf

        # volumeMounts:
        # - name: app-conf
        #   mountPath: /var/www/.env
        #   subPath: .env

      # volumes:
      # - name: app-conf
      #   configMap: 
      #     name: app-conf
      #     items: 
      #       - key: env
      #         path: .env